### ISSUE TITLE
[FEATURE REQUEST] Just an idea to have JSON schema validator integrated

### ISSUE THREAD

**Issue by jpalala** [mayajs/mongo#3]
## 📝 Description

I'd love for the framework to have something like https://github.com/serby/schemata integrated, allowing for API's schemas to be validated easily.

For example if you have a cars api  and you can only post with certain validations (the car make and model  is not empty etc etctera) 

This would be useful for  basic JSON-api model validations.

## 📋 Todo:

- [ ] Convert code found to typescript
- [ ] Figure out what basic schemas we'd like to support as example
- [ ] publish as a validator

**Comment by Mackignacio** [comment]
MayaJS is using [mongoose](https://mongoosejs.com/docs/guide.html#definition) under the hood. But I really like the idea of doing this without any library. But for now I think I let the mongoose library do all the validation for all the schema.
