### ISSUE TITLE
FEAT: Add schema on Mongodb options

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/mongo#6]
## 📝 Description
We want to declare the models inside each database instance. Each instance will required different models. Not all instance will have the same models.

### Sample Code
```js
Mongo({
    connectionString: env.MONGO_CONNECTION_URL,
    schemas: [ // Accepts an array of schema object
        {
           name: string; // Name of the model
           schema: Schema; // An instance of Mongoose Schema
           options?: MongoModelOptions; //  Mongo model options i              
         }, // Model that will be used by this mongodb instance
     ]
})
```

## 📋 Todo:

- [x] Create an SchemaObject interface
- [x] Add schema in MongodbOptions
- [x] Create a mapper function that create a model for each schema

## 🔍 Additional Info
This feature is required to make MayaJS more modular in nature.
