### ISSUE TITLE
FEAT: Multiple mongodb instance

### ISSUE THREAD

**Issue by Mackignacio** [mayajs/mongo#8]
## 📝 Description

It is very nice if we can have a feature to create multiple mongodb instance with different connection string. This is also compliment the other pending issue with the core mayajs library that will support multiple database types.

## 📋 Todo:

- [x] Create a database list
- [x] Ability to define multiple connection instance
- [x] Each connection has different models but can share schemas
- [x] Can reference each db connection
